FROM mongo:latest
RUN apt-get update; apt-get install curl; apt-get install -y kafkacat
COPY config-replica.js config-data.js source-connector.json sink-connector.json initialize-container.sh /
RUN chmod +x initialize-container.sh
