FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y curl; apt-get install -y kafkacat
# install mongosh
RUN curl https://downloads.mongodb.com/compass/mongosh_0.11.0_amd64.deb -o mongosh.deb && \
    dpkg --install mongosh.deb
COPY source-connector.json sink-connector.json sink-connector-cdc.json initialize-container.sh /
RUN chmod +x initialize-container.sh
